//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 01:57:07 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "lm.teleapps.com/SOAP", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.teleapps.lm.soap;
